server:
  port: 9002

spring:
  config:
    import: queryconfig.yml
  datasource:
    url: jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=AVQFile
    username: sa
    password: eswar
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none 
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        generate_statistics: true
        jdbc:
          batch_size: 30
        dialect: org.hibernate.dialect.SQLServerDialect

#####File Configurations#####
file:
  header: HEADER
  trailer: TRAILER
  detail: DETAIL
  headerFilePath: D:/Work/AvqFiles/pwgldhdr
  trailerFilePath: D:/Work/AvqFiles/pwgldtlr
  detailFilePath: D:/Work/AvqFiles/pwgldinf
  databaseType: AVQFile.dbo
